# Diff-style snippet against the existing main.py. Only the marked
# lines are new; sql_guard/generate_sql/phrase_answer are unchanged.

import auth  # <-- NEW
from access_guard import check_restricted_columns, AccessDenied  # <-- NEW
from sql_guard import UnsafeQueryError
from llm import generate_sql, phrase_answer
import db


def ask(question: str, login_id: str):  # <-- CHANGED: now takes login_id
    print("\nThinking...")

    try:
        sql, provider, raw_model_output = generate_sql(question)
    except UnsafeQueryError as e:
        print(f"\n[BLOCKED] The generated query was rejected for safety reasons:\n{e}")
        return

    try:                                                    # <-- NEW block
        check_restricted_columns(sql, login_id)
    except AccessDenied as e:
        print(f"\n[BLOCKED] {e}")
        return

    print(f"[info] SQL generated by: {provider}")
    print(f"[info] Query: {sql}")

    try:
        columns, rows = db.run_query(sql, login_id)         # <-- CHANGED: now passes login_id
    except AccessDenied as e:                                # <-- NEW: distinct from a real DB error
        print(f"\n[BLOCKED] {e}")
        return
    except Exception as e:
        print(f"\n[ERROR] Query failed to execute against the database:\n{e}")
        return

    answer = phrase_answer(question, sql, columns, rows, provider)
    print(f"\nAnswer:\n{answer}")


def main():
    print("=" * 60)
    print("Staffing Data Q&A Pipeline (test mode)")
    print("Type a question in plain English, or 'exit' to quit.")
    print("=" * 60)

    login_id = auth.get_login_id_cli()  # <-- NEW: prompted once, reused every question

    while True:
        question = input("\n> ").strip()
        if question.lower() in ("exit", "quit"):
            print("Goodbye.")
            break
        if not question:
            continue
        ask(question, login_id)  # <-- CHANGED: login_id threaded through


if __name__ == "__main__":
    main()