"""
Command-line entry point for the staffing-data Q&A pipeline.

Flow per question:
  1. Take a plain-English question from the user.
  2. Ask an LLM (Groq/Llama 3.3 first, OpenAI as fallback) to write SQL
     against the masked view.
  3. Validate that SQL is safe (SELECT-only, masked view only).
  4. Run it against MySQL using the restricted read-only DB user.
  5. Ask an LLM to phrase the raw results as a plain-English answer.
  6. Print the answer (and, for transparency, the SQL + provider used).

Run with:  python main.py
"""

from sql_guard import UnsafeQueryError
from llm import generate_sql, phrase_answer
import db


def ask(question: str):
    print("\nThinking...")

    # Step 1-3: generate + validate SQL (handles Groq->OpenAI fallback internally)
    try:
        sql, provider, raw_model_output = generate_sql(question)
    except UnsafeQueryError as e:
        print(f"\n[BLOCKED] The generated query was rejected for safety reasons:\n{e}")
        return

    print(f"[info] SQL generated by: {provider}")
    print(f"[info] Query: {sql}")

    # Step 4: execute
    try:
        columns, rows = db.run_query(sql)
    except Exception as e:
        print(f"\n[ERROR] Query failed to execute against the database:\n{e}")
        return

    # Step 5: phrase the answer
    answer = phrase_answer(question, sql, columns, rows, provider)

    print(f"\nAnswer:\n{answer}")


def main():
    print("=" * 60)
    print("Staffing Data Q&A Pipeline (test mode)")
    print("Type a question in plain English, or 'exit' to quit.")
    print("=" * 60)

    while True:
        question = input("\n> ").strip()
        if question.lower() in ("exit", "quit"):
            print("Goodbye.")
            break
        if not question:
            continue
        ask(question)


if __name__ == "__main__":
    main()
