"""
Validates any SQL generated by the LLM BEFORE it is ever executed.

This is the real safety net for the whole pipeline -- it does not rely on
the LLM "behaving." Even if the model is tricked, confused, or just makes a
mistake, queries that don't pass these checks are rejected outright and
never reach the database.
"""

import re
from tables.registry import allowed_table_names

# Statement types that must NEVER be allowed to run, under any circumstance.
FORBIDDEN_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE",
    "CREATE", "REPLACE", "GRANT", "REVOKE", "RENAME", "CALL",
    "EXEC", "EXECUTE", "SET ", "LOAD_FILE", "INTO OUTFILE", "INTO DUMPFILE",
]

# A crude but effective table-name extractor: looks for tokens following
# FROM or JOIN. Not a full SQL parser, but sufficient as a safety layer on
# top of the DB-level permission restriction (the real backstop).
TABLE_PATTERN = re.compile(r"\b(?:FROM|JOIN)\s+`?([a-zA-Z0-9_]+)`?", re.IGNORECASE)


class UnsafeQueryError(Exception):
    """Raised when a generated SQL query fails validation."""
    pass


def validate_sql(sql: str) -> str:
    """
    Validates a SQL string. Returns the cleaned SQL if it's safe.
    Raises UnsafeQueryError with a clear reason if it's not.
    """
    if not sql or not sql.strip():
        raise UnsafeQueryError("Empty SQL was generated.")

    cleaned = sql.strip().rstrip(";")

    # Must start with SELECT (allow leading whitespace/comments to be simple
    # about it -- we just check the first meaningful word).
    first_word = cleaned.strip().split(None, 1)[0].upper()
    if first_word != "SELECT":
        raise UnsafeQueryError(
            f"Only SELECT statements are allowed. Got a statement starting "
            f"with '{first_word}'."
        )

    # Reject if it contains multiple statements (stacked queries).
    if ";" in sql.strip().rstrip(";"):
        raise UnsafeQueryError("Multiple SQL statements are not allowed.")

    upper_sql = cleaned.upper()
    for bad_word in FORBIDDEN_KEYWORDS:
        word = bad_word.strip()
        # Word-boundary match, not naive substring -- a plain "in" check
        # would false-positive on legitimate SQL like "OFFSET" (contains
        # "SET"), "RESET", or a column named e.g. "asset_value".
        if re.search(rf"\b{re.escape(word)}\b", upper_sql):
            raise UnsafeQueryError(
                f"Query contains a forbidden keyword: '{word}'."
            )

    # Check every referenced table is on the allow-list. This list is built
    # dynamically from whatever tables/*.py files are registered+enabled --
    # adding a new table elsewhere never requires touching this file.
    allowed = allowed_table_names()
    referenced_tables = set(TABLE_PATTERN.findall(cleaned))
    disallowed = {t for t in referenced_tables if t.lower() not in
                  {a.lower() for a in allowed}}
    if disallowed:
        raise UnsafeQueryError(
            f"Query references table(s) not on the allow-list: {disallowed}. "
            f"Only {allowed} may be queried."
        )

    if not referenced_tables:
        raise UnsafeQueryError(
            "Could not confirm which table this query touches -- rejecting "
            "to be safe."
        )

    return cleaned


def enforce_row_limit(sql: str, max_rows: int = 500) -> str:
    """
    Ensures a LIMIT clause is present, adding one if missing, so a runaway
    query can never return an unbounded number of rows.
    """
    if re.search(r"\bLIMIT\s+\d+\b", sql, re.IGNORECASE):
        return sql
    return f"{sql} LIMIT {max_rows}"